# Generated by Django 3.2.6 on 2021-11-03 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20211102_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='task_r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.task'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='user_r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.user_field'),
        ),
    ]
